import { useState, type FormEvent } from 'react'
import { useAuth } from './useAuth'

type AuthPanelProps = { open: boolean; onClose: () => void }

export function AuthPanel({ open, onClose }: AuthPanelProps) {
  const { user, accessToken, busy, message, error, login, refresh, check, logout } = useAuth()
  const [username, setUsername] = useState('admin')
  const [password, setPassword] = useState('qwerty')

  async function submitLogin(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await login(username, password) }
  if (!open) return null

  return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-foreground/70 p-4 pt-16 backdrop-blur-md sm:pt-24" onClick={onClose}><section className="w-full max-w-lg rounded-[2rem] border border-border bg-card p-6 text-card-foreground shadow-2xl sm:p-8" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-5 border-b border-border pb-5"><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-muted-foreground">Проверка AuthX</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.05em]">Вход в аккаунт</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Проверьте авторизацию и права доступа.</p></div><button type="button" onClick={onClose} className="grid size-9 place-items-center rounded-full border border-border text-xl transition hover:bg-secondary" aria-label="Закрыть">×</button></div>
    {!user ? <form className="mt-7 space-y-5" onSubmit={(event) => void submitLogin(event)}><label className="block" htmlFor="auth-username"><span className="mb-2 block text-xs font-semibold text-muted-foreground">Логин</span><input id="auth-username" name="username" value={username} onChange={(event) => setUsername(event.target.value)} className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none transition focus:border-ring focus-visible:ring-2 focus-visible:ring-ring" autoComplete="username" spellCheck={false} /></label><label className="block" htmlFor="auth-password"><span className="mb-2 block text-xs font-semibold text-muted-foreground">Пароль</span><input id="auth-password" name="password" value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none transition focus:border-ring focus-visible:ring-2 focus-visible:ring-ring" type="password" autoComplete="current-password" /></label><button disabled={busy} className="w-full rounded-full bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground transition hover:bg-secondary hover:text-secondary-foreground disabled:cursor-wait disabled:opacity-60">{busy ? 'Входим…' : 'Войти'}</button><p className="text-center text-xs text-muted-foreground">Демо: <b>admin / qwerty</b> или <b>user / qwerty</b></p></form> : <div className="mt-7 space-y-4"><div className="rounded-2xl border border-border bg-muted p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Текущий пользователь</p><p className="mt-2 text-2xl font-semibold">{user.username}</p><span className="mt-3 inline-flex rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">Роль: {user.role}</span></div><div className="grid gap-2 sm:grid-cols-2"><button type="button" disabled={busy} onClick={() => void check('/api/auth/me')} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold transition hover:bg-secondary">Проверить профиль</button><button type="button" disabled={busy} onClick={() => void refresh()} className="rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground transition hover:bg-secondary hover:text-secondary-foreground">Обновить токен</button><button type="button" disabled={busy} onClick={() => void check('/api/auth/user-area')} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold transition hover:bg-secondary">Доступ пользователя</button><button type="button" disabled={busy} onClick={() => void check('/api/auth/admin-only')} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold transition hover:bg-secondary">Доступ администратора</button></div><button type="button" onClick={() => void logout()} className="w-full rounded-full border border-border px-5 py-3.5 text-sm font-semibold transition hover:bg-secondary">Выйти</button></div>}
    {message && <p role="status" aria-live="polite" className="mt-5 rounded-xl border border-border bg-muted px-4 py-3 text-xs leading-5 text-muted-foreground">{message}</p>}{error && <p role="alert" aria-live="polite" className="mt-3 rounded-xl border border-border bg-secondary px-4 py-3 text-xs leading-5 text-secondary-foreground">{error}</p>}{accessToken && <p className="mt-4 truncate font-mono text-[10px] text-muted-foreground">Токен в памяти: {accessToken.slice(0, 22)}…</p>}
  </section></div>
}
